apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fraud-api-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-fraud-api
spec:
  type: {{ .Values.fraudApi.service.type }}
  selector:
    app: {{ .Release.Name }}-fraud-api
  ports:
    - name: http
      port: {{ .Values.fraudApi.service.port }}
      targetPort: {{ .Values.fraudApi.service.port }}
      protocol: TCP
---
{{- if .Values.demo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-demo-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-demo
spec:
  type: {{ .Values.demo.service.type }}
  selector:
    app: {{ .Release.Name }}-demo
  ports:
    - name: http
      port: {{ .Values.demo.service.port }}
      targetPort: {{ .Values.demo.service.port }}
      protocol: TCP
{{- end }}
